answers = [
    'It is certain',
    'It is decidedly so',
    'Reply hazy, try again',
    'Don’t count on it ',
    'Ask again later',
    'As I see it, yes',
    'Most likely',
    'My reply is no',
    'Without a doubt',
    'Yes — definitely',
    'My sources say no',
    'Better not tell you now',
    'Cannot predict now',
    'Outlook good',
    'Outlook not so good',
    'Signs point to yes',
    'Yes',
    'Concentrate and ask again',
    'Very doubtful',
    'You may rely on it'
]
